name: hostloc checkin

on:
  schedule:
    # 每天执行3次
    - cron: "00 */12 * * *"
  workflow_dispatch:

env:
  HOSTLOC_USERNAME: ${{secrets.HOSTLOC_USERNAME}}
  HOSTLOC_PASSWORD: ${{secrets.HOSTLOC_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3.10

      - name: Set up Python
        uses: actions/setup-python@3.10
        with:
          python-version: 3.10

      - name: Run checkin
        run: python3 hostloc_auto_get_points.py

