name: hostloc checkin

on:
  schedule:
    # 每天执行3次
    - cron: "00 */12 * * *"
  workflow_dispatch:

env:
  REFRESH_TOKENS: ${{secrets.REFRESH_TOKENS}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Run checkin
        run: python3 hostloc_auto_get_points.py

