name: hostloc checkin

on:
  schedule:
    # 每天执行3次
    - cron: "00 */12 * * *"
  workflow_dispatch:

env:
  HOSTLOC_USERNAME: ${{secrets.HOSTLOC_USERNAME}}
  HOSTLOC_PASSWORD: ${{secrets.HOSTLOC_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Python 3.1
        run: python -m pip install python==3.1

      - name: Compile Python 3.1 for x64
        run: python -m pip install python-dist
        run: python setup.py build --build-type=release

      - name: Run checkin
        run: python3 hostloc_auto_get_points.py

